name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compilar testes
        run: gcc -o testes testes.c trabalhocarlos.c

      - name: Executar testes
        run: ./testes


